services:
  backend:
    build: ./app
    command: gunicorn killnet73.wsgi:application --bind 0.0.0.0:8002
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - ./.env
    ports:
      - '8002:8002'
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "ailab_db"
      POSTGRES_USER: "luxar"
      POSTGRES_PASSWORD: "sYst3m0ps"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
  media_volume: