# Generated by Django 4.1 on 2022-09-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='vk', help_text='Первые две буквы соц сети', max_length=2, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка на социальную сеть')),
            ],
            options={
                'verbose_name': 'Социальные сети',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
